-- basic vim level settings
vim.cmd('set termguicolors')
vim.cmd('syntax enable')
vim.cmd('set splitbelow')
vim.cmd('set splitright')
vim.cmd('set exrc')
vim.cmd('set secure')
vim.cmd('set nocompatible')
vim.cmd('set nowrap')
vim.cmd('set foldmethod=indent')
vim.cmd('set foldlevel=1')
vim.cmd('set showmatch')  
vim.cmd('set ignorecase')
vim.cmd('set mouse=v')  
vim.cmd('set incsearch')
vim.cmd('set tabstop=2')
vim.cmd('set softtabstop=2')
vim.cmd('set expandtab')   
vim.cmd('set shiftwidth=2')
vim.cmd('set scrolloff=16')
vim.cmd('set autoindent') 
vim.cmd('set number')    
vim.cmd('set wildmode=longest,list')
vim.cmd('filetype plugin indent on')
vim.cmd('syntax on')               
vim.cmd('set hidden')
vim.cmd('set mouse=a')
vim.cmd('set clipboard=unnamedplus')
vim.cmd('set cursorline')          
vim.cmd('set ttyfast')            
-- vim.opt.relativenumber=true
vim.opt.smartindent=true
vim.opt.hlsearch=false
vim.cmd('vnoremap p "_dP')
